#!/bin/bash

ssh lucas@46.101.204.162 \
    '   set -e
        set -x
        cd ~/draft.sx
        git fetch
        git reset --hard origin/master
        sudo docker-compose build
        sudo /bin/systemctl restart draftsx
        sudo /bin/systemctl status draftsx
    '
